First_Site/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include("homepage.urls")),
]

homepage/urls.py
from django.conf.urls import url
from . import views


app_name = 'homepage'

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^about/$', views.about, name="about"),
    url(r'^projects/$', views.projects, name="projects"),
    #download urls
    url(r'^projects/download/(?P<filename>[\w\-\.]+)/$', views.download, name="download"),
]


homepage/models.py
from django.db import models


class ProjectSRC(models.Model):
    filename = models.CharField(unique=True, max_length=40)
    location = models.CharField(max_length=50)
    size = models.CharField(max_length=5)


class ProjectBinary(models.Model):
    filename = models.CharField(max_length=40)
    location = models.CharField(max_length=50)
    size = models.CharField(max_length=6)

homepage/views.py
from django.shortcuts import render, get_object_or_404
from django.core.files import File
from django.shortcuts import HttpResponse
from . models import *
from django.conf import settings
import os


def index(request):
    return render(request, 'index.html')


def projects(request):
    binary_objects = ProjectBinary.objects.all()
    src_objects = ProjectSRC.objects.all()

    context = {'binary_objects': binary_objects, 'src_objects': src_objects}
    return render(request, 'projects.html', context=context)


def about(request):
    return render(request, 'about.html')


def download(request, filename):
    if filename.find('-') == -1:
        path = settings.MEDIA_ROOT + filename
    else:
        path = settings.MEDIA_ROOT + "src/" + filename
    file = open(path, 'rb')
    download_file = File(file)

    response = HttpResponse(download_file, content_type='application/octet-stream')
    response['x-Sendfile'] = path
    response['Content-Length'] = os.stat(path).st_size
    response['Content-Disposition'] = 'attachment; filename=%s' % filename

    file.close()
    return response




homepage/templates/about.html
{% extends 'base_template.html' %}

{% block title %}
    <title>About</title>
{% endblock %}

{% block body %}
     <style> body{ background: linear-gradient(black, white);} </style>
     <div class="page-wrap">
         <div id="main" class="container clear-top">
            <div id="center" class="center-about-head">
                <div class="about-head">
                    <div class="row">
                        <div class="col-lg-4 col-md-4 col-sm-12">
                            {% load static %}
                            <img src="{% static 'images/profile.jpg' %}" alt="Profile">
                        </div>
                        <div class="col-lg-8 col-md-8 col-sm-12">
                            <h2 class="profile-heading">Mandla Masombuka</h2>
                            <h3 class="profile-sub-heading">Software Developer</h3>
                        </div>
                    </div>
                </div>
            </div>
             <div class="align-about-paragraph">
                 <div class="paragraphs">
                     <p>
                         I'm a software developer from Siyabuswa, a small place in Mpumalanga province. I currently
                         reside in Johannesburg. That's it... don't know what to say now.<br><br>
                         Oh I almost forgot, I really love programming and I basically made this website just
                         to introduce myself in the web development theme. I plan to venture more in web dev, maybe
                         pick up more of Javascript's front-end libraries like React.js then move on to Android
                         development.
                     </p>
                 </div>
             </div>
         </div>
     </div>
{% endblock %}





homepage/templates/base_projects_panel.html
{% extends 'base_template.html' %}

{% block title %}
    <title>Projects</title>
{% endblock title %}

{% block body %}
    <div class="page-wrap">
        <div id="main" class="container">
            {% block panel %}
                <div class="projects-panel">
                    <div class="panel-header">
                        {% block panelHeader %} {% endblock panelHeader %} <!-- <h3>Zombie Apocalypse</h3> -->
                        {% block headerSub %} {% endblock headerSub %}
                        <!-- <p class="panel-header-sub"><span class="span">Type: </span>Game</p> -->
                    </div>
                    <div class="screenshot">
                        {% block image %} {% endblock image %}
                        {% comment %} <!-- <img src="{% static 'images/zombies.jpg' %}" alt="Screen shot"> --> {% endcomment %}
                    </div>
                    {% block download %} {% endblock download %}
                    <!-- <a class="span" href="#">Download source folder</a><br> -->
                    <p class="inline span">Description: </p>
                    {% block description %}{% endblock description %}
                    <!-- <p class="description"></p> -->
                </div>
            {% endblock panel %}
            </div>
        </div>
    </div>

{% endblock body %}


homepage/templates/base_template.html
<!DOCTYPE html>
<html lang="en">
{% block head %}
<head>
    {% block title %}
    {% endblock %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    {% load staticfiles %}
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/base_custom_css.css' %}" rel="stylesheet">

    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <script>
        $(document).ready(function () {
            var url = window.location;
            $('ul.nav a').filter(function () {
                return this.href == url;
            }).parent().addClass('active').parent().parent().addClass('active');
        });
    </script>
</head>
{% endblock head %}

<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#NavBar" aria-expanded="false">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'homepage:index' %}"> Code Dumpster</a>
            </div>

            <div class="collapse navbar-collapse" id="NavBar">
                <ul class="nav navbar-nav" >
                    <li>
                        <a href="{% url 'homepage:index' %}">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'homepage:projects' %}">Projects</a>
                    </li>
                    <li>
                        <a href="{% url 'homepage:about' %}">About</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% block body %}{% endblock %}

    {% block footer %}
    <div class="myfooter">
        <div class="container">
            <div class="row">
                <div class="col-md-6 footer-panel">
                    <h4><strong>Contact Details</strong></h4>
                    <div class="row-md">
                        <div class="col-sm">
                            <p class="myfooter-text-color"><a>mandlamasombuka21@gmail.com</a></p>
                        </div>
                    </div>
                    <div class="row-md">
                        <div class="col-sm">
                            <p class="myfooter-text-color">(+27)61 785 9409</p>
                        </div>
                    </div>
                </div>

                <div class="col-md-6 footer-panel">
                    <h4><strong>Social</strong></h4>
                    <div class="row">
                        <div class="col-md-12 col-sm-12">
                            <ul class="list-inline links">
                                <li>
                                    <a href="https://facebook.com/mandla.masombuka.35" target="_blank">
                                        <i class="fa fa-facebook"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="https://instagram.com/__mandla__/" target="_blank">
										<i class="fa fa-instagram"></i>
									</a>
                                </li>
                                <li>
                                    <a href="https://linkedin.com/in/mandla-masombuka-940065148" target="_blank"><i class="fa fa-linkedin"></i></a>
                                </li>
                            </ul>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock footer%}
</body>
</html>

homepage/templates/index.html
{% extends 'base_template.html' %}

{% block title %}
    <title>Code Dumpster</title>
{% endblock %}

{% block body %}
    <div class="page-wrap">
        <div id="main" class="container clear-top">
            <div class="row">
                <div class="col">
                    <div class="heading">
                        <h1 id="top-heading"> Welcome to my mini projects dump site </h1>
                    </div>
                    <p class="paragraphs index-paragraph-align">
                        This is where I generally dump my <i>"profile building projects"</i>. Most of the programs I
                        built are written in Java and C++. I felt these
                        <a href="{% url 'homepage:projects' %}">projects</a> weren't really GitHub material so
                        I decided to just dump them here on my site. <br><br>
                        This is website is written using Python's Django framework, which is really awesome.
                    </p>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

homepage/templates/projects.html
{% extends 'base_template.html' %}

{% block title %}
    <title>Projects</title>
{% endblock title %}

{% block body %}
    {% load static %}
    <style> body{ background: linear-gradient(black, white);} </style>
    <div class="page-wrap">
        <div id="main" class="container">
            <div class="row">
                <div class="col-sm-6 col-md-6 col-lg-6">
                    <div class="projects-panel">
                        <div class="panel-header">
                            <h3>Zombie Apocalypse</h3>
                            <p class="panel-header-sub"><span class="span">Type: </span>Game</p>
                        </div>
                        <div id="re" class="screenshot">
                            <a href="#">
                                <img src="{% static 'images/zombies.jpg' %}" alt="Screen shot">
                            </a>
                        </div>

                        {% for object in src_objects|slice:"0:1" %}
                            <a class="span" href="{{object.location}}">Download source folder ({{object.size}} KB)</a> or
                        {% endfor %}
                        {% for object in binary_objects|slice:"0:1" %}
                            <a class="span" href="{{object.location}}">compiled exe file ({{object.size}} MB)</a><br>
                        {% endfor %}

                        <p class="inline span">Description: </p>
                        <p class="description">
                            This is one of the games i've managed to complete, though not perfect, it's my favourite!
                            I wrote it in the first semester of Java programming. I ended up not submitting because it
                            took forever to complete :-(
                        </p>
                    </div>
                </div>

                <div class="col-sm-6 col-md-6 col-lg-6">
                    <div class="projects-panel">
                        <div class="panel-header">
                            <h3>Multiplayer Tanks</h3>
                            <p class="panel-header-sub"><span class="span">Type: </span>Multiplayer game</p>
                        </div>
                        <div class="screenshot">
                            <img src="{% static 'images/tanks.jpg' %}" alt="Screen shot">
                        </div>

                        {% for object in src_objects|slice:"6:7" %}
                            <a class="span" href="{{object.location}}">Download source folder ({{object.size}} KB)</a> or
                        {% endfor %}
                        {% for object in binary_objects|slice:"6:7" %}
                            <a class="span" href="{{object.location}}">compiled exe file ({{object.size}} MB)</a><br>
                        {% endfor %}

                        <p class="inline span">Description: </p>
                        <p class="description">
                            This one was written in the second semester of Java programming. It's a
                            multiplayer and I'm really proud to have pulled something like this. But i know
                            it's going to be very slow playing over a network since I used TCP and not UDP plus
                            it's Java.
                        </p>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-6 col-md-6 col-lg-6">
                    <div class="projects-panel">
                        <div class="panel-header">
                            <h3>Pong</h3>
                            <p class="panel-header-sub"><span class="span">Type: </span>Game</p>
                        </div>
                        <div class="screenshot">
                             <img src="{% static 'images/pong.jpg' %}" alt="Screen shot">
                        </div>

                        {% for object in src_objects|slice:"3:4" %}
                            <a class="span" href="{{object.location}}">Download source folder ({{object.size}} KB)</a> or
                        {% endfor %}
                        {% for object in binary_objects|slice:"3:4" %}
                            <a class="span" href="{{object.location}}">compiled exe file ({{object.size}} MB)</a><br>
                        {% endfor %}

                        <p class="inline span">Description:</p>
                        <p class="description">
                            My first love. The first and last C++ game I've written. Definitely one of the worst
                            spaghetti code ever written. Do not try to understand what I was doing, you'll hurt your
                            brain. In my defence, it was the first year I started writing code.
                        </p>
                    </div>
                </div>

                <div class="col-sm-6 col-md-6 col-lg-6">
                    <div class="projects-panel">
                        <div class="panel-header">
                            <h3>Hangman</h3>
                            <p class="panel-header-sub"><span class="span">Type: </span>Console game</p>
                        </div>
                        <div class="screenshot">
                             <img src="{% static 'images/hangman.jpg' %}" alt="Screen shot">
                        </div>

                        {% for object in src_objects|slice:"2:3" %}
                            <a class="span" href="{{object.location}}">Download source folder ({{object.size}} KB)</a> or
                        {% endfor %}
                        {% for object in binary_objects|slice:"2:3" %}
                            <a class="span" href="{{object.location}}">compiled exe file ({{object.size}} MB)</a><br>
                        {% endfor %}

                        <p class="inline span">Description: </p>
                        <p class="description">
                            This one over here is a product of boredom. So one day I was seating, bored, I decided
                            to try to write a Python console game within an hour and voila hangman!
                        </p>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-6 col-md-6 col-lg-6">
                    <div class="projects-panel">
                        <div class="panel-header">
                            <h3>NSFAS Accommodations finder</h3>
                            <p class="panel-header-sub"><span class="span">Type: </span>Software</p>
                        </div>
                        <div class="screenshot">
                             <img src="{% static 'images/accommodations.jpg' %}" alt="Screen shot">
                        </div>

                        {% for object in src_objects|slice:"1:2" %}
                            <a class="span" href="{{object.location}}">Download source folder ({{object.size}} KB)</a> or
                        {% endfor %}
                        {% for object in binary_objects|slice:"1:2" %}
                            <a class="span" href="{{object.location}}">compiled exe file ({{object.size}} MB)</a><br>
                        {% endfor %}

                        <p class="inline span">Description: </p>
                        <p class="description">
                            This is one software I've made which is quite helpful to other people, well not yet cause
                            it has been on my laptop the whole time. It helps with directions to UJ's NSFAS
                            accredited student accommodations. Plus it can be used to find the closest accommodations
                            to any of the UJ's campuses. Written with Java of course with some custom Tree and Array
                            list data structures.
                        </p>
                    </div>
                </div>

                <div class="col-sm-6 col-md-6 col-lg-6">
                    <div class="projects-panel">
                        <div class="panel-header">
                            <h3>Online shop</h3>
                            <p class="panel-header-sub"><span class="span">Type: </span>Software</p>
                        </div>
                        <div class="screenshot">
                             <img src="{% static 'images/onlineShop.jpg' %}" alt="Screen shot">
                        </div>

                        {% for object in src_objects|slice:"5:6" %}
                            <a class="span" href="{{object.location}}">Download source folder ({{object.size}} KB)</a> or
                        {% endfor %}
                        {% for object in binary_objects|slice:"5:6" %}
                            <a class="span" href="{{object.location}}">compiled exe file ({{object.size}} MB)</a><br>
                        {% endfor %}

                        <p class="inline span">Description: </p>
                        <p class="description">
                            Another client-server program. I wrote this one for a friend. It implements a simple
                            first-come first-served algorithm for placing order. the algorithm is implemented using
                            a Queue data structure. <b>Disclaimer: </b> The prices here are made up.
                        </p>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-6 col-md-6 col-lg-6">
                    <div class="projects-panel">
                        <div class="panel-header">
                            <h3>Rename project</h3>
                            <p class="panel-header-sub"><span class="span">Type: </span>Console software</p>
                        </div>
                        <div class="screenshot">
                             <img src="{% static 'images/rename.jpg' %}" alt="Screen shot">
                        </div>

                        {% for object in src_objects|slice:"4:5" %}
                            <a class="span" href="{{object.location}}">Download source folder ({{object.size}} KB)</a> or
                        {% endfor %}
                        {% for object in binary_objects|slice:"4:5" %}
                            <a class="span" href="{{object.location}}">compiled exe file ({{object.size}} MB)</a><br>
                        {% endfor %}

                        <p class="inline span">Description: </p>
                        <p class="description">
                            I have always wanted to create an application to help me rename the files for TV series'
                            after I downloaded them. With this software you basically give it the format in which you
                            want the series' files to be renamed and it will rename all of them.
                        </p>
                    </div>
                </div>

                <div class="col-sm-6 col-md-6 col-lg-6">
                    <div class="projects-panel">
                        <div class="panel-header">
                            <h3>YouCalculus</h3>
                            <p class="panel-header-sub"><span class="span">Type: </span>Software</p>
                        </div>
                        <div class="screenshot">
                             <img src="{% static 'images/youcalculus.jpg' %}" alt="Screen shot">
                        </div>

                        {% for object in src_objects|slice:"7:" %}
                            <a class="span" href="{{object.location}}">Download source folder ({{object.size}} KB)</a> or
                        {% endfor %}
                        {% for object in binary_objects|slice:"7:" %}
                            <a class="span" href="{{object.location}}">compiled exe file ({{object.size}} MB)</a><br>
                        {% endfor %}

                        <p class="inline span">Description: </p>
                        <p class="description">
                            Here, is a YouTube wannabe application I created when I was introducing myself to Graph
                            data structure. This application is for tutoring calculus using videos from YouTube. It's
                            not yet done though. The main use of the graph (undirected) in this application is to
                            show the related videos of the currently watched video. This application has great potential
                            for being a good resource for studying, unlike looking for the videos directly on YouTube
                            which will show up the video you want along with some random video with irresistible title.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock body %}
